services:
  api-insumos:
    image: backend-insumos-ts:latest
    container_name: api-insumos-ts
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.50'
        reservations:
          memory: 64M
    env_file:
      - .env
    ports:
      - "3333:3333"
